name: 📘 test-docs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  docs:
    name: Validate mkdocs links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # use the latest stable version
          python-version: "3.x"
          cache: "pip"
      # `pybtex` uses `pkg_resources` which is deprecated. Use workaround until upstream `mkdocs_bibtext`decides on a solution
      # https://github.com/shyamd/mkdocs-bibtex/issues/228
      # https://bitbucket.org/pybtex-devs/pybtex/issues/169/replace-pkg_resources-with
      - run: pip install -r docs/requirements.txt setuptools
      - run: mkdocs build --strict
        working-directory: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_MKDOCS_GIT_COMMITTERS: False
